### ISSUE TITLE
当内存报警告时，存储的资源会被释放掉。

### ISSUE THREAD

**Issue by fsp1990** [SpringOx/ANKeyValue#1]
[ANKeyValueTable tableWithName:@"xxx" version:@"0.0.1" resumable:NO];   这样初始化。

内存较低时（<16.49%）数据会被释放掉， 这是崩溃的栈信息

 libsystem_kernel.dylib 0x3a607090  __chmod + 8
1   Foundation  0x301a5238  __NSCleanupTemporaryFile + 168
2   Foundation  0x3019836a  +[NSKeyedArchiver archiveRootObject:toFile:] + 238
3   batiaoyuappios  0x001c3b94  -[ANPersistentData archive:](ANPersistentData.m:253)
4   batiaoyuappios  0x001c35c4  -[ANPersistentData syncArchive](ANPersistentData.m:137)
5   batiaoyuappios  0x001c353e  -[ANPersistentData archiveNow](ANPersistentData.m:123)
6   batiaoyuappios  0x001843f0  -[ANKeyValueTable dealloc](ANKeyValueTable.m:163)
7   libobjc.A.dylib 0x3a054b6a  objc_object::sidetable_release(bool) + 174
8   libobjc.A.dylib 0x3a0550d6  (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 358
9   CoreFoundation  0x2f6fec18  _CFAutoreleasePoolPop + 15
10  CoreFoundation  0x2f79417a  ___CFRunLoopRun + 1306

**Comment by SpringOx** [comment]
多谢反馈！该反馈帮助我发现了一个比较严重的内存管理缺陷，已经及时fixed：
Commits on Oct 4, 2015
@SpringOx
加强persistent data内部对sender(调用者)的内存管理，避免sender被提前释放导致的各种稳定性问题
SpringOx authored 3 minutes ago
